#!/bin/sh

# PROVIDE: swapexd
# REQUIRE: DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swapexd"
	rcvar=`set_rcvar`

stop_cmd="swapexd_stop"
start_cmd="swapexd_start"

load_rc_config $name

: ${swapexd_enable=NO}

swapexd_start()
{
        if [ -e "/var/run/swapexd.pid" ]
        then
          echo "swapexd already running?"
          swapexd_stop
        fi

        echo "Starting swapexd..."
        (/usr/local/sbin/swapexd -d -p >/dev/null 2>/dev/null) &
}

swapexd_stop()
{
        echo "Stoping swapexd..."
        if [ -e "/var/run/swapexd.pid" ]
        then
          PID=`cat /var/run/swapexd.pid`
          kill -9 $PID
          rm /var/run/swapexd.pid
        fi        
}

run_rc_command "$1"


