#include "portUtils.h"
QStringList makefileorder = {"PORTNAME", "PORTVERSION", "CATEGORIES", "MASTER_SITES", "MASTER_SITE_SUBDIR", "PKGNAMEPREFIX", "PKGNAMESUFFIX", "DISTNAME", "EXTRACT_SUFX", "DISTFILES", "EXTRACT_ONLY", \
					"PATCH_SITES", "PATCHFILES", "MAINTAINER", "COMMENT", "RUN_DEPENDS" };

QStringList PortUtils::generateNewMakefile(QString name, QString version, QString category, QString mastersite, QString maintainer, QString comment){
  //This generates a "quick porting" Makefile template that can be added on to later
  QStringList out;
  out << "# Port template generated by EasyPort version 1.0";
  out << "# $FreeBSD$";
  out << "";
  out << "# General Port information #";
  out << "PORTNAME=\t"+name;
  out << "PORTVERSION=\t"+version;
  out << "CATEGORIES=\t"+category;
  out << "MASTER_SITES=\t"+mastersite;
  out << "";
  out << "MAINTAINER=\t"+maintainer;
  out << "COMMENT=\t"+comment;
  out << "";
  out << ".include <bsd.port.mk>"

  return out;
}

QStringList PortUtils::findPortCategories(QString portdir){
  //search through the available ports tree and find the valid categories
  QStringList cats;
  
  return cats;
}
